"""Linked models with relationships

Revision ID: 03d379141b0c
Revises: d9ff07ed5da5
Create Date: 2026-10-10 12:45:39.305434

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '03d379141b0c'
down_revision: Union[str, Sequence[str], None] = 'd9ff07ed5da5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('position_okei',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('okei_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['okei_id'], ['okei.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('position_id', 'okei_id')
    )
    op.create_table('characteristic_value_okei',
    sa.Column('characteristic_value_id', sa.String(), nullable=False),
    sa.Column('okei_id', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_value_id'], ['characteristic_values.id'], ),
    sa.ForeignKeyConstraint(['okei_id'], ['okei.id'], ),
    sa.PrimaryKeyConstraint('characteristic_value_id', 'okei_id')
    )
    op.drop_table('okpd2')
    op.add_column('characteristic_values', sa.Column('characteristic_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'characteristic_values', 'characteristics', ['characteristic_id'], ['id'])
    op.add_column('characteristics', sa.Column('position_id', sa.String(), nullable=False))
    op.create_foreign_key(None, 'characteristics', 'positions', ['position_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'characteristics', type_='foreignkey')
    op.drop_column('characteristics', 'position_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'characteristic_values', type_='foreignkey')
    op.drop_column('characteristic_values', 'characteristic_id')
    op.create_table('okpd2',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('okpd2_pkey'))
    )
    op.drop_table('characteristic_value_okei')
    op.drop_table('position_okei')
    # ### end Alembic commands ###
