"""Changed min_val, max_val to range field

Revision ID: 69a678dcca1d
Revises: 03d379141b0c
Create Date: 2026-10-10 13:37:12.730130

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '69a678dcca1d'
down_revision: Union[str, Sequence[str], None] = '03d379141b0c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristic_values', sa.Column('range', postgresql.NUMRANGE(), nullable=True))
    op.drop_column('characteristic_values', 'max_value')
    op.drop_column('characteristic_values', 'min_value')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristic_values', sa.Column('min_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.add_column('characteristic_values', sa.Column('max_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_column('characteristic_values', 'range')
    # ### end Alembic commands ###
