"""Added measurement column for values

Revision ID: 6c8b8622a7ad
Revises: c81be98f1b8d
Create Date: 2026-10-10 14:55:57.008986

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '6c8b8622a7ad'
down_revision: Union[str, Sequence[str], None] = 'c81be98f1b8d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristic_values', sa.Column('measure_units', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characteristic_values', 'measure_units')
    # ### end Alembic commands ###
