"""Initial revision

Revision ID: 8beca4a8438d
Revises: 
Create Date: 2026-10-10 17:45:55.831608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '8beca4a8438d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('okei',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('positions',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('required', sa.Boolean(), nullable=False),
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('position_okei',
    sa.Column('position_id', sa.String(), nullable=False),
    sa.Column('okei_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['okei_id'], ['okei.id'], ),
    sa.ForeignKeyConstraint(['position_id'], ['positions.id'], ),
    sa.PrimaryKeyConstraint('position_id', 'okei_id')
    )
    op.create_table('characteristic_values',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('measure_units', sa.String(), nullable=True),
    sa.Column('is_range', sa.Boolean(), nullable=False),
    sa.Column('range', postgresql.NUMRANGE(), nullable=True),
    sa.Column('is_quality', sa.Boolean(), nullable=False),
    sa.Column('quality_description', sa.String(), nullable=True),
    sa.Column('characteristic_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_id'], ['characteristics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('characteristic_value_okei',
    sa.Column('characteristic_value_id', sa.Integer(), nullable=False),
    sa.Column('okei_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['characteristic_value_id'], ['characteristic_values.id'], ),
    sa.ForeignKeyConstraint(['okei_id'], ['okei.id'], ),
    sa.PrimaryKeyConstraint('characteristic_value_id', 'okei_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('characteristic_value_okei')
    op.drop_table('characteristic_values')
    op.drop_table('position_okei')
    op.drop_table('characteristics')
    op.drop_table('positions')
    op.drop_table('okei')
    # ### end Alembic commands ###
