"""Added name for characteristic value

Revision ID: c81be98f1b8d
Revises: 69a678dcca1d
Create Date: 2026-10-10 14:37:41.635861

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'c81be98f1b8d'
down_revision: Union[str, Sequence[str], None] = '69a678dcca1d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('characteristic_values', sa.Column('name', sa.String(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('characteristic_values', 'name')
    # ### end Alembic commands ###
